---
- name: install base packages
  apt: pkg={{ item }} state=present
  with_items:
    - python-software-properties
    - dpkg-dev
    - wget
    - build-essential
    - vim
    - byobu
    - ntp
    - sudo
    - ufw
    - fail2ban
    - openssh-client
    - openssh-server
    - rsync
    - python{{ python_version }}-dev
    - libffi-dev
    - libssl-dev

- name: ensure that the admin and login groups are present
  group: name={{ item }} state=present system=yes
  with_items:
    - admin
    - login

- name: allow admin group users to sudo
  copy: src=admin dest=/etc/sudoers.d/admin owner=root mode=0440

- name: allow ssh through firewall
  ufw: rule=allow port=ssh

- name: ensure ufw is turned on
  ufw: state=enabled policy=deny

- name: ensure fail2ban is turned on
  service: name=fail2ban state=started

- name: configure fail2ban
  copy: src=jail.local dest=/etc/fail2ban/jail.local owner=root mode=0644
  notify:
    - restart fail2ban

- name: add github to the ssh known hosts
  lineinfile: line="{{ lookup('file', 'github.pub') }}"
              dest=/etc/ssh/ssh_known_hosts
              state=present
              create=yes
              owner=root
              mode=0644

- name: set the locale to utf8
  lineinfile: line={{ item }} dest=/etc/default/locale state=present create=yes owner=root mode=0644
  with_items:
    - "LC_ALL=en_US.UTF-8"
    - "LANG=en_US.UTF-8"

- name: ensure that dev users are present
  user: name={{ item.name }} shell=/bin/bash groups=admin,login append=yes generate_ssh_key=no
  with_items: users

- name: add ssh keys for dev users
  authorized_key: user={{ item.0.name }} key="{{ item.1 }}"
  with_subelements:
    - users
    - public_keys

# Now that we've hopefully configured some non-root users to be able to ssh
# in, update the sshd config, which (among other things) will disable root
# logins.
- name: configure sshd
  copy: src=sshd_config dest=/etc/ssh/sshd_config owner=root mode=0644
  notify:
    - restart sshd

