---
- name: add rabbitmq repo
  apt_repository: repo="deb http://www.rabbitmq.com/debian/ testing main" state=present

- name: add the rabbitmq repo key
  apt_key: url="http://www.rabbitmq.com/rabbitmq-signing-key-public.asc" state=present

- name: install rabbitmq-server
  apt: name=rabbitmq-server state=present

- name: ensure rabbitmq is running
  service: name=rabbitmq state=started

- name: remove guest rabbitmq user
  rabbitmq_user: user=guest state=absent
  notify:
    - restart rabbitmq

- name: configure rabbitmq
  copy: src=rabbitmq.config
        dest=/etc/rabbitmq/rabbitmq.config
        owner=root
        group=root
        mode=644
  notify:
    - restart rabbitmq

- name: add rabbitmq vhost
  rabbitmq_vhost: name={{ project_name }}_{{ env_name }} state=present
  notify:
    - restart rabbitmq

- name: add rabbitmq user
  rabbitmq_user: user={{ project_name }}_{{ env_name }}
                 password={{ broker_password }}
                 vhost={{ project_name }}_{{ env_name }}
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
                 force=yes
  notify:
    - restart rabbitmq

- name: allow the app minions through the firewall for rabbitmq
  ufw: rule=allow port=5672 from_ip={{ hostvars[item].ansible_eth0.ipv4.address }}
  with_items: app_minions
