---
- name: install memcached
  apt: name=memcached state=present

- name: ensure memcached is running
  service: name=memcached state=started

- name: allow the app minions through the firewall for memcached
  ufw: rule=allow port=11211 from_ip={{ hostvars[item].ansible_eth0.ipv4.address }}
  with_items: app_minions
