---
# file: tequila/deploy.yml
#
# This playbook will deploy an entire environment
#
- hosts: all
  pre_tasks:
    - name: apt update
      apt: update_cache=yes
  roles:
    - common

# Other roles should NOT express dependencies on the `common` role.
# We will always apply it here.

# Each of these plays should include a single, high-level role.
# If other ansible roles are needed for that high-level role to work, make
# them dependencies of that ansible role rather than adding it to the play
# here. That way all the information about what that high-level role needs
# is in one place, not divided between here and there.
- hosts: db-master
  roles:
    - db-master

- hosts: worker
  roles:
    - worker

- hosts: web
  roles:
    - web

- hosts: cache
  roles:
    - cache

- hosts: queue
  roles:
    - queue

- hosts: worker
  roles:
    - worker
