---
- name: install postgres server
  apt: name={{ item }} state=present
  with_items:
    - postgresql-contrib-{{ pg_version }}
    - postgresql-server-dev-{{ pg_version }}
    - postgresql-client-{{ pg_version }}
    - libpq-dev
    - postgresql-{{ pg_version }}
    - python-psycopg2

- name: remove the postgres meta-package
  apt: name=postgresql state=absent

- name: ensure postgres is running
  service: name=postgresql state=started

# The postgres < 9.3 problem with the default encoding not being utf8
# isn't a problem with Ansible >= 1.6.  Hopefully.
# ref: https://github.com/ansible/ansible/issues/7246

- name: configure postgres authentication
  template: src="pg_hba.conf"
            dest=/etc/postgresql/{{ pg_version }}/main/pg_hba.conf
            owner=postgres group=postgres mode=0640
  notify:
    - reload postgres

- name: configure postgres server
  template: src="postgresql.conf"
            dest=/etc/postgresql/{{ pg_version }}/main/postgresql.conf
            owner=postgres group=postgres mode=0644
  notify:
    - restart postgres

- name: allow app minions through the firewall
  ufw: rule=allow port=5432 from_ip={{ hostvars[item].ansible_eth0.ipv4.address }}
  with_items: app_minions
